### ISSUE TITLE
Fix remaining issues from studenthub-ui-mock repo

### ISSUE THREAD

**Issue by sbunciak** [StudentHubCZ/studenthub-portal#115]
- [ ] [Add paging to all views with a table or a list](https://github.com/StudentHubCZ/studenthub-ui-mock/issues/56)
- [ ] [Fix paging](https://github.com/StudentHubCZ/studenthub-ui-mock/issues/48)
- [ ] [Replace tag inputs with a more user friendly component](https://github.com/StudentHubCZ/studenthub-ui-mock/issues/46)
- [ ] [Add PDF export to topic details](https://github.com/StudentHubCZ/studenthub-ui-mock/issues/43)
- [ ] [Implement Company Management](https://github.com/StudentHubCZ/studenthub-ui-mock/issues/41)
- [ ] [Integrate 'Forgot password' with API](https://github.com/StudentHubCZ/studenthub-ui-mock/issues/34)
- [ ] [Introduce tier selection in company registration form](https://github.com/StudentHubCZ/studenthub-ui-mock/issues/28)
- [ ] [Enable search in Universities view](https://github.com/StudentHubCZ/studenthub-ui-mock/issues/22)
- [ ] [Fix disabled cursor in dropdowns](https://github.com/StudentHubCZ/studenthub-ui-mock/issues/5)
- [ ] [Add HTML5 Form constraints](https://github.com/StudentHubCZ/studenthub-ui-mock/issues/4)
